SQL>CREATE TABLE BRANCH(B_NO NUMBER(4) PRIMARY KEY, MANAGER_ID NUMBER(4), B_ADD VARCHAR(40), B_CITY VARCHAR(40), CONTACT_NO NUMBER(10));/*create branch table*/
SQL>INSERT INTO BRANCH VALUES(1,991,'DAUJI ROAD','BIKANER',9876546789);
SQL>INSERT INTO BRANCH VALUES(2,992,'VYAS COLONY','BIKANER',8967896574);
/*insert multiple rows at a time*/
INSERT INTO BRANCH
(B_NO , MANAGER_ID , B_ADD , B_CITY, CONTACT_NO);
VALUES
  (3,993,'RANI BAZAR','BIKANER',6789456767); 
  (4,994,'MP COLONY','BIKANER',6367895678);

/*create employee table*/
SQL>CREATE TABLE EMPLOYEE(B_NO NUMBER(4), EMP_ID NUMBER(4), EMP_NAME VARCHAR(40), EMP_POSITION VARCHAR(40), EMP_SALARY NUMBER(5), FOREIGN KEY(B_NO) REFERENCES BRANCH);
SQL>INSERT INTO EMPLOYEE VALUES(1,1,'REKHA SINGH','MANAGER',30000);
SQL>INSERT INTO EMPLOYEE VALUES(1,2,'SALIM HUSAIN','LIBRARIAN',20000);
SQL>INSERT INTO EMPLOYEE VALUES(1,3,'RAMESH AGARWAL','PROFESSOR',40000);
/*create multiple rows at a time*/
INSERT INTO EMPLOYEE
(B_NO, EMP_ID , EMP_NAME, EMP_POSITION, EMP_SALARY);
VALUES
(1,4,'POONAM GUPTA','PROFESSOR',45000);
(1,5,'VIVEK KUMAR','WORKER',25000);

/*create books table*/
SQL>CREATE TABLE BOOKS(B_ID NUMBER(4) PRIMARY KEY, ISBN VARCHAR(13),B_TITLE VARCHAR(40),AUTHER VARCHAR(40),PUBLISHER VARCHAR(40),EDITION VARCHAR(5));
SQL>INSERT INTO BOOKS VALUES(2201,8976677123,'FUNDAMENTALS OF COMPUTERS','RAJRAMAN V','PHI',NULL);
SQL>INSERT INTO BOOKS VALUES(2202,6787564534,'DATABASE MANAGEMENT SYSTEM','MAJUMDAR & BHATACHARYA','TMH','Vth');
SQL>INSERT INTO BOOKS VALUES(2203,NULL,'LET US C++','KANETKAR Y','BPB PUBLICATION',NULL);
/*create multiple rows at a time*/
INSERT INTO BOOKS
(B_ID, ISBN,B_TITLE,AUTHER,PUBLISHER,EDITION);
VALUES
(2204,8181564539,'INDUSTRIAL LAWS','Dr RL NAULAKHA',NULL,'IInd');
(2205,8867564567,'THE BIOLOGY OF BELIFE','BRUCE H LIPTON','HAY HOUSE INDIA',NULL);

/*create studend table*/
SQL>CREATE TABLE STUDENT(STU_ID NUMBER(4) PRIMARY KEY,STU_NAME VARCHAR(40), STU_ADD VARCHAR(40), REG_DATE DATE NOT NULL);
SQL>INSERT INTO STUDENT VALUES(1001,'YASH BOHRA','JNV COLONY','1 JULY 2017');
SQL>INSERT INTO STUDENT VALUES(1002,'CHRISTY M CHACKO','TILAK NAGAR','10 JULY 2017');
SQL>INSERT INTO STUDENT VALUES(1003,'SHREYA DAS','KARNI NAGAR','5 AUGUST 2017');
/*create multiple rows at a time*/
INSERT INTO STUDENT 
(STU_ID,STU_NAME, STU_ADD, REG_DATE);
VALUES
(1004,'ANJALI GUPTA','MP COLONY','12 JULY 2017');
(1005,'SANJNA CHAYHAN','KUCHILPURA','1 AUGUST 2017');

/*create issue_status table*/
SQL>CREATE TABLE ISSUE_STATUS(STU_ID NUBER(4), ISSUE_ID NUMBER(4), B_NO NUMBER(4), ISSUE_DATE DATE NOT NULL,ISSUE_B_NAME VARCHAR(40), FOREIGN KEY(STU_ID) REFERENCES STUDENT,FOREIGN KEY(B_ID) REFERENCES BOOKS);
SQL>INSERT INTO ISSUE_STATUS VALUES(1001,331,2212,'1 OCT 2017','DATA & NETWORK COMMUNICATION');
SQL>INSERT INTO ISSUE_STATUS VALUES(1005,332,2217,'5 OCT 2017','FUNDAMENTALS OF COMPUTERS');

/*create return_status table*/
SQL>CREATE TABLE RETURN_STATUS(STU_ID NUBER(4), RETURN_ID NUMBER(4), B_NO NUMBER(4), RETURN_DATE DATE NOT NULL,RETURN_B_NAME VARCHAR(40), FOREIGN KEY(STU_ID) REFERENCES STUDENT,FOREIGN KEY(B_ID) REFERENCES BOOKS);
SQL>INSERT INTO RETURN_STATUS VALUES(1018,441,2202,'3 OCT 2017','INTRODUCTION TO COMPUTER');
SQL>INSERT INTO RETURN_STATUS VALUES(1010,351,2208,'13 NOV 2017','PROGRAMMING IN JAVA');
commit;